on: [push]

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: build pkg
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: build pkg
        id: build
        uses: ./.github/actions/build
        with:
          version: '0.${{ github.run_number }}.${{ github.run_attempt }}'
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v0.${{ github.run_number }}.${{ github.run_attempt }}"
          prerelease: true
          title: "v0.${{ github.run_number }}.${{ github.run_attempt }}"
          files: |
            sha256sums
            profiles.json
            feeds.buildinfo
            config.buildinfo
            version.buildinfo
            feilongwrt-22.03-snapshot-unknown-sunxi-cortexa7-friendlyarm_nanopi-r1.manifest
            feilongwrt-22.03-snapshot-unknown-sunxi-cortexa7-friendlyarm_nanopi-r1-squashfs-sdcard.img.gz
            feilongwrt-22.03-snapshot-unknown-sunxi-cortexa7-friendlyarm_nanopi-r1-ext4-sdcard.img.gz
