on: [push]

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: build pkg
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: build pkg
        id: build
        uses: ./.github/actions/build
        with:
          version: '0.${{ github.run_number }}.${{ github.run_attempt }}'
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v0.${{ github.run_number }}.${{ github.run_attempt }}"
          prerelease: true
          title: "v0.${{ github.run_number }}.${{ github.run_attempt }}"
          files: |
            src/openwrt/bin/targets/sunxi/cortexa7/sha256sums
            src/openwrt/bin/targets/sunxi/cortexa7/profiles.json
            src/openwrt/bin/targets/sunxi/cortexa7/feeds.buildinfo
            src/openwrt/bin/targets/sunxi/cortexa7/config.buildinfo
            src/openwrt/bin/targets/sunxi/cortexa7/version.buildinfo
            src/openwrt/bin/targets/sunxi/cortexa7/feilongwrt-22.03-*.manifest
            src/openwrt/bin/targets/sunxi/cortexa7/feilongwrt-22.03-*.img.gz
